site_name: chimakidash tech page
site_description: 'chimakidash tech page'
site_author: 'chimakidash'
docs_dir: docs/
repo_name: 'chimakidash/chimakidash.github.io'
repo_url: 'https://chimakidash.github.io/.'
nav:
    - Home: index.md
    - DNS: dns.md
theme:
  name: 'material'
